### ISSUE TITLE
Allow variables in YAML definition of sql batches

### ISSUE THREAD

**Issue by mkrcah** [datadudes/athena#26]
Sometimes it is needed to perform several sql batches with queries with are almost identical but differ in one parameter. For example:

```
- query: SELECT * FROM foo WHERE bar = 'Spark rocks!'
  output: spark.csv
- query: SELECT * FROM foo WHERE bar = 'Impala rocks!'
  output: impala.csv
- query: SELECT * FROM foo WHERE bar = 'Hadoop rocks!'
  output: hadoop.csv
```

Especially for complex sql queries, it would be very useful to provide a mechanism in the YAML batch-sql config to define a for-loop and provide a placeholder in the `query` and `output` parameter. 

For example, we might follow the path that [Ansible chose for loops](http://docs.ansible.com/playbooks_loops.html):

```
- query: SELECT * FROM foo WHERE bar = '{{item}} rocks!'
  with_items:
  - "Spark"
  - "Impala"
  - "Hadoop"
  output: {{item}}.csv
```
